var express = require('express');
var app = express();

app.use(require('stylus').middleware(process.argv[3] ));
app.use(express.static(process.argv[3]))


app.listen(process.argv[2]);

// HTML without styles is boring so this exercise will teach you how to use Stylus with Express on the fly.
//
// Style the HTML from the "STATIC" exercise using Stylus middleware.
// Stylus <https://github.com/stylus/stylus> generates .css files on-the-fly from
// .styl files.
//
// Your solution should listen on the port supplied by process.argv[2] for
// GET requests, one of which will be for main.css, which should be
// automatically generated by your Stylus middleware. index.html and main.styl
// can be found in process.argv[3] (they are in the same directory).
//
